apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: aks-demo
spec:
  replicas: 2

  selector:
    matchLabels:
      app: fastapi-app

  template:
    metadata:
      labels:
        app: fastapi-app

    spec:
      containers:
        - name: fastapi

          image: aksacrdev02.azurecr.io/aks-mysql-sample:dfdfd2faa8ae2de54bcbe594024b98a432f1e681

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_HOST

            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_PORT

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_PASSWORD

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000

            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 30
            periodSeconds: 15

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"