apiVersion: v1
kind: Service
metadata:
  name: image-generator
  namespace: image-generator
spec:
  selector:
    app.kubernetes.io/name: image-generator
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
